- name: Install HAProxy
  ansible.builtin.apt:
    package: haproxy
    state: present
    update_cache: true
  notify: Restart HAProxy

- name: Template HAProxy config
  ansible.builtin.template:
    src: 'haproxy_config.j2'
    dest: '/etc/haproxy/haproxy.cfg'
    owner: root
    mode: '644'
  notify: Reload HAProxy
